src/apps/restaurant/urls.py
from django.urls import path
from .views import (
    materials, recipes, preparations, menu, profile
)

app_name = 'restaurant'

urlpatterns = [
    path('materials/', materials.RawMaterialsListView.as_view(), name='raw_materials'),
    path('materials/category/add/', materials.AddMaterialCategoryView.as_view(), name='add_material_category'),
    path('materials/category/delete/', materials.DeleteMaterialCategoryView.as_view(), name='delete_material_category'),
    path('materials/add/', materials.AddRawMaterialView.as_view(), name='add_raw_materials'),
    path('materials/<int:pk>/edit/', materials.EditRawMaterialView.as_view(), name='edit_raw_materials'),
    path('materials/delete/', materials.DeleteRawMaterialView.as_view(), name='delete_raw_materials'),
    path('materials/<int:pk>/form/', materials.MaterialReduceFormView.as_view(), name='raw_materials_reduce_form'),

    path('recipes/', recipes.FoodsRecipesView.as_view(), name='recipes'),
    path('recipes/category/add/', recipes.AddRecipesCategoryView.as_view(), name='add_recipe_category'),
    path('recipes/category/delete/', recipes.DeleteRecipeCategoryView.as_view(), name='delete_recipe_category'),
    path('recipes/add/', recipes.AddRecipeView.as_view(), name='add_recipe'),
    path('recipes/delete/', recipes.DeleteRecipeView.as_view(), name='delete_recipe'),
    path('recipes/<int:pk>/', recipes.RecipeDetailsView.as_view(), name='recipe_details'),
    path('recipes/<int:pk>/edit/', recipes.EditRecipeView.as_view(), name='edit_recipe'),
    path('recipes/material/add/', recipes.AddRecipeMaterialsView.as_view(), name='add_recipe_materials'),
    path('recipes/material/<int:pk>/edit/', recipes.EditRecipeMaterialsView.as_view(), name='edit_recipe_materials'),
    path('recipes/<int:pk>/material/delete/', recipes.DeleteRecipeMaterialView.as_view(),
         name='delete_recipe_material'),
    path('recipes/<int:pk>/get-price/', recipes.GetRecipeFinalPriceView.as_view(), name='get_recipe_final_price'),

    path('preparations/', preparations.PreparationsView.as_view(), name='preparations'),
    path('preparations/category/add/', preparations.AddPreparationCategoryView.as_view(),
         name='add_preparation_category'),
    path('preparations/category/delete/', preparations.DeletePreparationCategoryView.as_view(),
         name='delete_preparation_category'),
    path('preparations/add/', preparations.AddPreparationView.as_view(), name='add_preparation'),
    path('preparations/delete/', preparations.DeletePreparationView.as_view(), name='delete_preparation'),
    path('preparations/<int:pk>/', preparations.PreparationDetailsView.as_view(), name='preparation_details'),
    path('preparations/<int:pk>/edit', preparations.EditPreparationView.as_view(), name='edit_preparation'),
    path('preparations/material/add/', preparations.AddPreparationMaterialsView.as_view(),
         name='add_preparation_materials'),
    path('preparations/material/<int:pk>/edit/', preparations.EditPreparationMaterialsView.as_view(),
         name='edit_preparation_materials'),
    path('preparatoins/<int:pk>/material/delete/', preparations.DeletePreparationMaterialView.as_view(),
         name='delete_preparation_material'),
    path('preparations/<int:pk>/get-price/', preparations.GetPreparationFinalPriceView.as_view(),
         name='get_preparation_final_price'),

    path('menu/', menu.MenuEngineeringView.as_view(), name='menu_engineering'),
    path('menu/services-fee/update/', menu.UpdateServicesFeeView.as_view(), name='update_services_fee'),
    path('menu/recipe/<int:pk>/update/', menu.UpdateRecipeView.as_view(), name='update_recipe'),

    path('profile/index', profile.Index.as_view(), name='profile_index'),

    path('profile/add-or-update', profile.AddOrUpdateProfileView.as_view(), name='add_or_update_profile'),
    path('profile/fixed-costs/add', profile.AddFixedCostView.as_view(), name='add_fixed_cost'),
    path('profile/fixed-costs/<int:pk>/update', profile.UpdateFixedCostProfileView.as_view(), name='update_fixed_cost'),
    path('profile/fixed-costs/<int:pk>/delete', profile.DeleteFixedCostView.as_view(), name='delete_fixed_cost'),

    path('profile/ongoing-costs/add', profile.AddOngoingCostView.as_view(), name='add_ongoing_cost'),
    path('profile/ongoing-costs/<int:pk>/update', profile.UpdateOngoingCostView.as_view(), name='update_ongoing_cost'),
    path('profile/ongoing-costs/<int:pk>/delete', profile.DeleteOngoingCostView.as_view(), name='delete_ongoing_cost'),

    path('profile/sales-estimate', profile.SalesEstimateView.as_view(), name='profile_sales_estimate'),
    path('profile/add-income-profile', profile.AddIncomeProfileView.as_view(), name='add_income_profile'),
    path('profile/update-income-profile/<int:pk>', profile.UpdateIncomeProfileView.as_view(), name='update_income_profile'),
    path('profile/delete-income-profile/<int:pk>', profile.DeleteIncomeProfileView.as_view(), name='delete_income_profile'),
]

src/config/urls.py
from django.conf.urls.static import static
from django.urls import path, include
from django.contrib import admin
from django.conf import settings

from azbankgateways.urls import az_bank_gateways_urls


urlpatterns = [
    path('admin/', admin.site.urls),
    path('tinymce/', include('tinymce.urls')),
    path('bankgateways/', az_bank_gateways_urls()),
    path('account/', include('apps.account.urls', namespace='account')),
    path('', include('apps.public.urls', namespace='public')),
    path('course/', include('apps.course.urls', namespace='course')),
    path('ticketing/', include('apps.ticket.urls', namespace='ticket')),
    path('customers/', include('apps.customers.urls', namespace='customers')),
    path('subscription/', include('apps.subscription.urls', namespace='subscription')),
    path('restaurant/', include('apps.restaurant.urls', namespace='restaurant')),
    path('payment/', include('apps.payment.urls', namespace='payment')),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/apps/restaurant/views/materials.py
from django.views.generic import TemplateView, FormView, View
from django.shortcuts import redirect, get_object_or_404, reverse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.utils.translation import gettext as _
from django.core.paginator import Paginator
from django.urls import reverse_lazy
from django.contrib import messages

from apps.subscription.mixinx import SubscriptionRequiredMixin
from apps.core.utils import toast_form_errors
from ..models import (Restaurant, RawMaterialCategory, RawMaterial)
from .. import forms


# Render RawMaterialsList view
class RawMaterialsListView(LoginRequiredMixin, TemplateView):
    template_name = 'restaurant/raw_materials.html'

    def filter(self, objects):
        cat_filter = self.request.GET.get('filter')
        if cat_filter:
            objects = objects.filter(category__title=cat_filter)
        return objects

    def pagination(self, objects):
        page_number = self.request.GET.get('page')
        paginator = Paginator(objects, 30)
        return paginator.get_page(page_number)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        restaurant = Restaurant.objects.get(user=self.request.user)

        # Get raw materials and filter them
        materials = RawMaterial.objects.filter(category__restaurant=restaurant).order_by('created_at')
        materials = self.filter(materials)
        page_obj = self.pagination(materials)

        context.update({
            'restaurant': restaurant,
            'page_obj': page_obj,
        })
        return context


# Add MaterialCategory view
class AddMaterialCategoryView(SubscriptionRequiredMixin, FormView):
    template_name = 'restaurant/raw_materials.html'
    form_class = forms.AddMaterialCategoryForm
    success_url = reverse_lazy('restaurant:raw_materials')

    def get_form(self, form_class=None):
        data = self.request.POST.copy()
        data.update({
            'restaurant': Restaurant.objects.get(user=self.request.user)
        })
        form_class = forms.AddMaterialCategoryForm(data=data, files=self.request.FILES)

        return form_class

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)

    def form_invalid(self, form):
        toast_form_errors(self.request, form)
        return redirect('restaurant:raw_materials')


# Delete MaterialCategory view
class DeleteMaterialCategoryView(SubscriptionRequiredMixin, View):
    """ Delete raw material category based on pk """
    def post(self, request):
        title = request.POST.get('title')

        try:
            restaurant = Restaurant.objects.get(user=request.user)
            obj = RawMaterialCategory.objects.get(restaurant=restaurant, title=title)
            obj.delete()
            messages.success(request, _('Category successfully deleted'))

        except (RawMaterialCategory.DoesNotExist, Restaurant.DoesNotExist):
            messages.error(request, _('There is an issue. please try again'))

        return redirect('restaurant:raw_materials')


# Add RawMaterial view
class AddRawMaterialView(SubscriptionRequiredMixin, FormView):
    template_name = 'restaurant/raw_materials.html'
    form_class = forms.RawMaterialForm
    success_url = reverse_lazy('restaurant:raw_materials')

    def form_valid(self, form):
        post = self.request.POST.copy()
        try:
            titles = post.getlist('title', [])
            uses = post.getlist('use_for', [])
            prices = post.getlist('price', [])
            categories = post.getlist('category', [])

            for index, item in enumerate(titles):
                data = {
                    'title': item,
                    'use_for': uses[index],
                    'price': prices[index],
                    'category': categories[index]
                }
                form = forms.RawMaterialForm(data=data)

                if form.is_valid():
                    form.save()

            messages.success(self.request, _('Raw materials added successfully'))

        except (IndexError, TypeError):
            messages.error(self.request, _('There is an issue. please try again'))

        return super().form_valid(form)


# Edit RawMaterial view
class EditRawMaterialView(SubscriptionRequiredMixin, FormView):
    template_name = 'restaurant/raw_materials.html'
    form_class = forms.RawMaterialForm
    success_url = reverse_lazy('restaurant:raw_materials')

    def get_form(self, form_class=None):
        data = self.request.POST.copy()
        instance = get_object_or_404(RawMaterial, pk=self.kwargs.get('pk'))

        return forms.RawMaterialForm(data=data, instance=instance)

    def form_valid(self, form):
        pk = self.kwargs.get('pk')
        restaurant = Restaurant.objects.get(user=self.request.user)
        
        if not RawMaterial.objects.filter(category__restaurant=restaurant, pk=pk).exists():
            return self.form_invalid(form)
        form.save()

        messages.success(self.request, _('Item successfully modified'))
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, _('There is an issue. please try again'))
        return redirect('restaurant:raw_materials')


# Delete RawMaterial view
class DeleteRawMaterialView(SubscriptionRequiredMixin, View):
    """ Delete raw material objects based on pk """
    def post(self, request):
        pk = self.request.POST.get('pk')

        restaurant = Restaurant.objects.get(user=self.request.user)
        obj = get_object_or_404(RawMaterial, category__restaurant=restaurant, pk=pk)
        obj.delete()

        messages.success(self.request, _("Item deleted successfully"))
        return redirect('restaurant:raw_materials')


# Render ReduceForm view
class MaterialReduceFormView(SubscriptionRequiredMixin, FormView):
    template_name = 'restaurant/reduce_form.html'
    model = RawMaterial
    form_class = forms.ReduceRawMaterialForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        queryset = RawMaterial.objects.filter(category__restaurant__user=self.request.user)
        context['object'] = get_object_or_404(queryset, pk=self.kwargs.get('pk'))

        return context

    def get_success_url(self):
        return reverse('restaurant:raw_materials_reduce_form', args=[self.kwargs.get('pk')])

    def get_form(self, form_class=None):
        data = self.request.POST.copy()
        instance = get_object_or_404(RawMaterial, pk=self.kwargs.get('pk'))

        return forms.ReduceRawMaterialForm(data=data, instance=instance)

    def form_valid(self, form):
        form.save(commit=False)
        messages.success(self.request, _('Items saved successfully. You can see results down below'))

        return super().form_valid(form)

src/apps/restaurant/views/menu.py
from django.shortcuts import get_object_or_404, reverse, redirect
from django.views.generic import TemplateView, View, FormView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Sum, F, PositiveIntegerField
from django.db.utils import DataError, DatabaseError
from django.utils.translation import gettext as _
from django.db.models.functions import Cast
from django.core.paginator import Paginator
from django.contrib import messages

from apps.subscription.mixinx import SubscriptionRequiredMixin
from ..models import (Restaurant, Recipe)
from .. import forms


# Render MenuEngineering view
class MenuEngineeringView(LoginRequiredMixin, TemplateView):
    template_name = 'restaurant/menu_engineering.html'

    def filter(self, objects):
        cat_filter = self.request.GET.get('filter')
        if cat_filter:
            objects = objects.filter(category__title=cat_filter)

        return objects

    def pagination(self, objects):
        page_number = self.request.GET.get('page')
        paginator = Paginator(objects, 15)
        return paginator.get_page(page_number)

    def get_context_data(self, object_list=None, **kwargs):
        context = super(MenuEngineeringView, self).get_context_data(**kwargs)
        restaurant = get_object_or_404(Restaurant, user=self.request.user)

        # Get recipes and filter them
        objects = Recipe.objects.filter(category__restaurant=restaurant, is_material=False).order_by('created_at')
        objects = self.filter(objects)
        page_obj = self.pagination(objects)

        context.update({
            'restaurant': restaurant,
            'page_obj': page_obj,
            'objects': objects.aggregate(
                total_final_price=Sum('final_price'),
                total_service_price=Sum('service_price'),
                total_price_with_factor=Sum('price_with_factor'),
                total_menu_price=Sum('menu_price'),
                total_item_profit=Sum('item_profit'),
                total_food_costs=Sum('food_cost'),
                total_number_sold=Sum('number_sold'),
                total_total_sales=Sum('total_sales'),
                total_total_cost=Sum('total_cost'),
                total_total_profit=Sum('total_profit'),
            ),
            'each_item_percentage_share': 0.7 / (objects.count() or 1),
        })

        return context


# Update Restaurant ServicesFee view
class UpdateServicesFeeView(SubscriptionRequiredMixin, View):
    """ Update restaurant services fee """

    def get_redirect_url(self, request):
        return reverse('restaurant:menu_engineering') + f'?filter={request.GET.get("filter")}'

    def post(self, request):
        fee = int(request.POST.get('services_fee'))
        restaurant = get_object_or_404(Restaurant, user=self.request.user)

        restaurant.services_fee = fee
        restaurant.save()

        # Update recipes service_prices based on services_fee
        recipes = Recipe.objects.filter(category__restaurant=restaurant, is_material=False)
        recipes.update(service_price=Cast(F('final_price') * (fee / 100), output_field=PositiveIntegerField()))
        recipes.update(price_with_factor=Cast(F('final_price') * F('factor') + F('service_price'), output_field=PositiveIntegerField()))

        messages.success(request, _('Services fee updated'))
        return redirect(self.get_redirect_url(request))  # Redirect with GET parameters


# UpdateRecipe view
class UpdateRecipeView(SubscriptionRequiredMixin, FormView):
    template_name = 'restaurant/menu_engineering.html'
    form_class = forms.UpdateRecipeForm

    def get_success_url(self):
        return reverse('restaurant:menu_engineering') + f'?filter={self.request.GET.get("filter")}&page={self.request.GET.get("page")}'

    def get_form(self, form_class=None):
        obj = get_object_or_404(Recipe, category__restaurant__user=self.request.user, pk=self.kwargs.get('pk'))
        return forms.UpdateRecipeForm(data=self.request.POST, instance=obj)
    
    def form_valid(self, form):
        form.save(commit=False)
        
        messages.success(self.request, _('Item updated successfully'))
        return super().form_valid(form)

src/apps/restaurant/templates/restaurant/components/preparations/add_category.html
<div class="modal fade" tabindex="-1" id="addCategory" aria-labelledby="addCategoryLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <form method="POST" action="{% url 'restaurant:add_preparation_category' %}" style="background-color: #2d2c2c;"
              class="modal-content text-white border-white border-1 rounded-3">
            {% csrf_token %}
            <div class="modal-header">
                <h5 class="modal-title fw-semibold h4">افزودن دسته بندی</h5>
                <span role="button" class="bi bi-x-lg" data-bs-dismiss="modal" aria-label="Close"
                      style="-webkit-text-stroke: 0.5pt;"></span>
            </div>
            <div class="modal-body">
                <div class="d-flex flex-column form-group">
                    <label class="form-label" style="font-size: 14px;">
                        عنوان دسته
                        <input type="text" name="title" class="form form-control mt-1"
                               style="background-color: #fafafa;" required>
                    </label>
                </div>
            </div>
            <div class="modal-footer border-top-0">
                <button type="submit" class="btn btn-success fw-semibold w-100">ذخیره</button>
            </div>
        </form>
    </div>
</div>

src/apps/restaurant/templates/restaurant/components/preparations/add_materials.html
<div class="modal fade" tabindex="-1" id="addMaterials" aria-labelledby="addMaterialsLabel" aria-hidden="true">
    <div class="modal-dialog modal-fullscreen w-100">
        <form method="POST" action="{% url 'restaurant:add_preparation_materials' %}"
              class="modal-content bg-modal text-white border-white border-1 rounded-3">
            {% csrf_token %}
            <input type="hidden" name="pk" value="{{ object.pk }}">
            <div class="modal-header">
                <h5 class="modal-title fw-semibold h4">فرم افزودن مواد</h5>
                <span role="button" class="bi bi-x-lg mt-1 ms-1" data-bs-dismiss="modal" aria-label="Close"
                      style="-webkit-text-stroke: 0.5pt;"></span>
            </div>
            <div class="modal-body">
                <div id="materialsSection">
                    <div class="d-flex align-items-end gap-1 border-bottom border-1 border-light mt-1 mb-4">
                        <div class="d-flex flex-wrap gap-2 flex-grow-1 form-group">
                            <label class="form-label fs-13 flex-grow-1">
                                عنوان ماده اولیه
                                <select class="form-select f-input mt-1 select-inputs" name="raw_material" required>
                                    {% for obj in raw_materials %}
                                        <option value="{{ obj.id }}">{{ obj }}</option>
                                    {% endfor %}
                                </select>
                            </label>
                            <label class="form-label fs-13 flex-grow-1">
                                مقدار (کیلوگرم/عدد)
                                <input type="number" name="amount" step="any" required class="form form-control f-input mt-1">
                            </label>
                        </div>
                    </div>
                </div>
                <div class="w-100 mt-3">
                    <button type="button" class="btn btn-outline-secondary fw-semibold w-100" onclick="createAddSection()">
                        جدید +
                    </button>
                </div>
            </div>
            <div class="modal-footer border-top-0">
                <button type="submit" class="btn btn-success fw-semibold w-100">ثبت مواد</button>
            </div>
        </form>
    </div>
</div>

src/apps/restaurant/templates/restaurant/components/preparations/add_preparation.html
<div class="modal fade" tabindex="-1" id="addPreparation" aria-labelledby="addPreparationLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <form method="POST" action="{% url 'restaurant:add_preparation' %}" style="background-color: #2d2c2c;"
              class="modal-content text-white border-white border-1 rounded-3">
            {% csrf_token %}
            <div class="modal-header">
                <h5 class="modal-title fw-semibold h4">افزودن غدای جدید</h5>
                <span role="button" class="bi bi-x-lg" data-bs-dismiss="modal" aria-label="Close"
                      style="-webkit-text-stroke: 0.5pt;"></span>
            </div>
            <div class="modal-body">
                <div class="d-flex flex-column form-group">
                    <label class="form-label" style="font-size: 14px;">
                        عنوان محصول
                        <input type="text" name="title" class="form form-control mt-1"
                               style="background-color: #fafafa;" required>
                    </label>
                    <label class="form-label" style="font-size: 14px;">
                        دسته بندی
                        <select name="category" class="form-select mt-1" required>
                            {% for obj in restaurant.get_recipes_categories %}
                                <option value="{{ obj.pk }}" {% if obj.title == request.GET.filter %}selected{% endif %}>{{ obj.title }}</option>
                            {% endfor %}
                        </select>
                    </label>
                </div>
            </div>
            <div class="modal-footer border-top-0">
                <button type="submit" class="btn btn-success fw-semibold w-100">ذخیره</button>
            </div>
        </form>
    </div>
</div>

src/apps/restaurant/templates/restaurant/components/preparations/delete_category.html
<div class="modal fade" tabindex="-1" id="deleteCategory" aria-labelledby="deleteCategoryLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <form method="POST" action="{% url 'restaurant:delete_preparation_category' %}"
              class="modal-content bg-modal text-white border-white border-1 rounded-3">
            {% csrf_token %}
            <div class="modal-header">
                <span class="modal-title fw-semibold h4">حذف دسته بندی</span>
                <span role="button" class="bi bi-x-lg mt-1 ms-1" data-bs-dismiss="modal" aria-label="Close"
                      style="-webkit-text-stroke: 0.5pt;"></span>
            </div>
            <div class="modal-body">
                <input type="hidden" name="id" id="categoryId" value="None">
                <span style="font-size: 14px;">
                     آیا از حذف
                    <span id="categoryTitle" class="text-warning"></span>
                    اطمینان دارید؟
                </span>
            </div>
            <div class="modal-footer border-top-0">
                <button type="submit" class="btn btn-danger fw-semibold">بله حذف</button>
            </div>
        </form>
    </div>
</div>

src/apps/restaurant/templates/restaurant/components/preparations/delete_material.html
<div class="modal fade" tabindex="-1" id="deleteMaterial" aria-labelledby="deleteMaterialLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <form method="POST" action="{% url 'restaurant:delete_preparation_material' object.pk %}"
              class="modal-content bg-modal text-white border-white border-1 rounded-3">
            {% csrf_token %}
            <div class="modal-header">
                <span class="modal-title fw-semibold h4">حذف ماده افزوده</span>
                <span role="button" class="bi bi-x-lg mt-1 ms-1" data-bs-dismiss="modal" aria-label="Close"
                      style="-webkit-text-stroke: 0.5pt;"></span>
            </div>
            <div class="modal-body">
                <input type="hidden" name="id" id="materialId" value="None">
                <span style="font-size: 14px;">
                     آیا از حذف
                    <span id="materialTitle" class="text-warning"></span>
                    اطمینان دارید؟
                </span>
            </div>
            <div class="modal-footer border-top-0">
                <button type="submit" class="btn btn-danger fw-semibold">بله حذف</button>
            </div>
        </form>
    </div>
</div>

src/apps/restaurant/templates/restaurant/components/preparations/delete_preparation.html
<div class="modal fade" tabindex="-1" id="deletePreparation" aria-labelledby="deletePreparationLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <form method="POST" action="{% url 'restaurant:delete_preparation' %}"
              class="modal-content bg-modal text-white border-white border-1 rounded-3">
            {% csrf_token %}
            <div class="modal-header">
                <span class="modal-title fw-semibold h4">حذف غدا</span>
                <span role="button" class="bi bi-x-lg mt-1 ms-1" data-bs-dismiss="modal" aria-label="Close"
                      style="-webkit-text-stroke: 0.5pt;"></span>
            </div>
            <div class="modal-body">
                <input type="hidden" name="pk" id="foodId" value="-1">
                <span style="font-size: 14px;">
                     آیا از حذف
                    <span id="foodTitle" class="text-warning"></span>
                    اطمینان دارید؟
                </span>
            </div>
            <div class="modal-footer border-top-0">
                <button type="submit" class="btn btn-danger fw-semibold">بله حذف</button>
            </div>
        </form>
    </div>
</div>