src/apps/ticket/urls.py
from django.urls import path
from . import views


app_name = 'ticket'

urlpatterns = [
    path('', views.TicketListView.as_view(), name='ticket_list'),
    path('create/', views.TicketCreateView.as_view(), name='create_ticket'),
    path('<int:pk>/', views.TicketDetailsView.as_view(), name='ticket_details'),
    path('<int:pk>/message/', views.CreateMessageView.as_view(), name='ticket_create_message'),
]

src/config/urls.py
from django.conf.urls.static import static
from django.urls import path, include
from django.contrib import admin
from django.conf import settings

from azbankgateways.urls import az_bank_gateways_urls


urlpatterns = [
    path('admin/', admin.site.urls),
    path('tinymce/', include('tinymce.urls')),
    path('bankgateways/', az_bank_gateways_urls()),
    path('account/', include('apps.account.urls', namespace='account')),
    path('', include('apps.public.urls', namespace='public')),
    path('course/', include('apps.course.urls', namespace='course')),
    path('ticketing/', include('apps.ticket.urls', namespace='ticket')),
    path('customers/', include('apps.customers.urls', namespace='customers')),
    path('subscription/', include('apps.subscription.urls', namespace='subscription')),
    path('restaurant/', include('apps.restaurant.urls', namespace='restaurant')),
    path('payment/', include('apps.payment.urls', namespace='payment')),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/apps/ticket/models.py
from django.utils.translation import gettext as _
from django.contrib.auth import get_user_model
from django.shortcuts import reverse
from django.db import models

from .enums import TicketTypesEnum, TicketStatusEnum
from .utils import ticket_file_src
User = get_user_model()


# Tickets model
class Ticket(models.Model):
    Types = TicketTypesEnum
    Status = TicketStatusEnum

    user = models.ForeignKey(User, on_delete=models.SET_NULL, related_name='tickets', verbose_name=_('User'), null=True)
    title = models.CharField(_('Title'), max_length=128, default=_('No title'))
    type = models.CharField(_('Type'), max_length=64, choices=Types.choices, default=Types.GENERAL)
    status = models.CharField(_('Status'), max_length=32, choices=Status.choices, default=Status.OPEN)
    is_active = models.BooleanField(_('Active'), default=True)

    created_at = models.DateTimeField(_('Creation time'), auto_now_add=True)
    updated_at = models.DateTimeField(_('Update time'), auto_now=True)

    class Meta:
        verbose_name = _('Ticket')
        verbose_name_plural = _('Tickets')
        ordering = ('-id',)

    def __str__(self):
        return f'{self.title} - {self.user}'

    def get_created_date(self):
        return self.created_at.strftime('%Y-%m-%d')

    def get_type_label(self):
        return self.get_type_display()

    def get_messages(self):
        return self.messages.all()

    def get_absolute_url(self):
        return reverse('ticket:ticket_details', args=[self.pk])


# Ticket Messages model
class Messages(models.Model):
    ticket = models.ForeignKey(Ticket, on_delete=models.CASCADE, related_name='messages', verbose_name=_('Ticket'))
    user = models.ForeignKey(User, on_delete=models.SET_NULL, related_name='ticket_messages', verbose_name=_('User'), null=True)
    text = models.TextField(_('Text'), max_length=512)
    file = models.FileField(_('Related file'), upload_to=ticket_file_src, null=True, blank=True)

    created_at = models.DateTimeField(_('Creation time'), auto_now_add=True)
    updated_at = models.DateTimeField(_('Update time'), auto_now=True)

    class Meta:
        verbose_name = _('Ticket message')
        verbose_name_plural = _('Ticket messages')

    def __str__(self):
        return f'{self.ticket}'

    def get_created_date(self):
        return self.created_at.strftime('%Y-%m-%d')

src/apps/ticket/forms.py
from django.utils.translation import gettext as _
from django import forms

from .models import Ticket, Messages


# CreateTicket form
class CreateTicketForm(forms.ModelForm):
    text = forms.CharField(max_length=512, required=True, widget=forms.Textarea)
    file = forms.FileField(required=False, widget=forms.FileInput)

    class Meta:
        model = Ticket
        fields = ('user', 'title', 'type')

    def save(self, commit=True):
        obj = super().save(commit)
        ticket_text = self.cleaned_data.get('text')
        ticket_file = self.cleaned_data.get('file')

        Messages.objects.create(
            ticket=obj,
            user=obj.user,
            text=ticket_text,
            file=ticket_file)

        return obj


# CreateMessage form
class CreateMessageForm(forms.ModelForm):
    class Meta:
        model = Messages
        fields = ('ticket', 'user', 'text', 'file')

src/apps/ticket/views.py
from django.views.generic import FormView, ListView, DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.utils.translation import gettext as _
from django.shortcuts import reverse
from django.urls import reverse_lazy
from django.contrib import messages

from .models import Ticket
from . import forms


# Render TicketList view
class TicketListView(LoginRequiredMixin, ListView):
    template_name = 'ticket/ticket_list.html'
    model = Ticket
    context_object_name = 'tickets'

    def get_queryset(self):
        queryset = Ticket.objects.filter(is_active=True, user=self.request.user)
        return queryset


# Render TicketCreate view
class TicketCreateView(LoginRequiredMixin, FormView):
    template_name = 'ticket/tickets_create.html'
    form_class = forms.CreateTicketForm
    success_url = reverse_lazy('ticket:ticket_list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tickets'] = Ticket.objects.filter(is_active=True, user=self.request.user)
        return context

    def get_form(self, form_class=None):
        data = self.request.POST.copy()
        data.update({'user': self.request.user.id})
        form_class = forms.CreateTicketForm(data=data, files=self.request.FILES)

        return form_class

    def form_valid(self, form):
        form.save()
        messages.success(self.request, _('Ticket sent successfully'))
        return super().form_valid(form)


# Render TicketDetails view
class TicketDetailsView(LoginRequiredMixin, DetailView):
    template_name = 'ticket/ticket_details.html'
    model = Ticket
    context_object_name = 'ticket'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tickets'] = Ticket.objects.filter(is_active=True, user=self.request.user)

        return context


# CreateMessage view
class CreateMessageView(LoginRequiredMixin, FormView):
    template_name = 'ticket/ticket_details.html'
    form_class = forms.CreateMessageForm

    def get_success_url(self):
        return reverse('ticket:ticket_details', args=[self.kwargs.get('pk')])

    def get_form(self, form_class=None):
        data = self.request.POST.copy()
        data.update({'user': self.request.user.id, 'ticket': self.kwargs.get('pk')})
        form_class = forms.CreateMessageForm(data=data, files=self.request.FILES)

        return form_class

    def form_valid(self, form):
        form.save()

        messages.success(self.request, _('Message sent successfully'))
        return super().form_valid(form)

src/apps/ticket/templates/ticket/ticket_details.html
{% extends 'base_template.html' %}
{% load static %}
{% load filters %}


{% block title %}مدیرمدرن | تیکت ها{% endblock %}

{% block styles %}
    <link rel="stylesheet" href="{% static 'styles/tickets.css' %}">
    <link rel="stylesheet" href="{% static 'styles/menu.css' %}">
{% endblock %}

{% block content %}
    <!-- Start Sidebar menu -->
    {% include 'includes/menus/side_menu.html' %}
    <!-- .End Sidebar menu -->

    <div class="container-fluid col-md-10 pb-1">
        <main class="main w-100 p-md-4 p-2">
            <h5 class="fw-semibold text-white text-md-end text-center mt-3">تیکت ها</h5>

            <div class="d-flex gap-5 mt-md-4 mt-3">
                <!-- Start tickets section -->
                <div class="d-md-flex d-none flex-column p-2 ticket-main">
                    <div class="rounded-3 mb-3">
                        <a href="{% url 'ticket:create_ticket' %}" class="btn btn-warning w-100 fw-semibold">تیکت جدید</a>
                    </div>

                    <div class="ticket-self-box">
                        {% for obj in tickets %}
                            <a href="{{ obj.get_absolute_url }}" title="مشاهده" class="d-flex flex-column rounded-3 ticket-box
                                {% if obj == ticket %}ticket-box-selected{% endif %}">
                                <div class="ticket-tag {% if obj.status == 'open' %}bg-success{% else %}bg-danger{% endif %}">
                                    <small class="text-white">{{ obj.get_status_display }}</small>
                                </div>
                                <div class="text-white ticket-box-head">
                                    <h5>{{ obj.title }}</h5>
                                </div>
                                <div class="d-flex gap-4 py-2 px-3 text-white ticket-box-body">
                                    <div class="d-flex flex-column">
                                        <small class="opacity-75">شناسه</small>
                                        <span class="fw-semibold">{{ obj.id }}</span>
                                    </div>
                                    <div class="d-flex flex-column me-1">
                                        <small class="opacity-75">فعالیت</small>
                                        <span class="fw-semibold datetime-convert">{{ obj.get_created_date }}</span>
                                    </div>
                                    <div class="d-flex flex-column me-1">
                                        <small class="opacity-75">نوع</small>
                                        <span class="fw-semibold">{{ obj.get_type_label|truncatechars:11 }}</span>
                                    </div>
                                </div>
                            </a>
                        {% empty %}
                            <div class="w-100"></div>
                        {% endfor %}
                    </div>
                </div>
                <!-- .End tickets section -->

                <!-- Start ticket messages section -->
                <div class="d-flex flex-column gap-4 text-white w-100 mt-md-0 mt-2 ticket-detail-main ticket-message-main">
                    <div class="d-flex justify-content-between">
                        <span class="fw-semibold h5">{{ ticket.title }}</span>
                        <a href="{% url 'ticket:ticket_list' %}" class="btn btn-danger bi bi-x-lg pb-0 d-md-none d-block"></a>
                    </div>

                    <div class="d-flex flex-column gap-2 mt-2 w-100 h-100">
                        <div class="d-flex flex-column gap-4 ticket-message-all">
                            {% for obj in ticket.get_messages %}
                                <div class="d-flex flex-column gap-3 ticket-message-body {% if obj.user != request.user %}ticket-left{% endif %}">
                                    <div class="d-flex flex-column text-white">
                                        <span>{{ obj.user.profile.place_name|default:'مدیر سایت' }}</span>
                                        <small class="opacity-75 datetime-convert xs-text">
                                            {{ obj.get_created_date }}
                                        </small>
                                    </div>
                                    <div class="d-flex flex-column gap-1 text-white">
                                        <small>{{ obj.text }}</small>
                                        {% if obj.file %}
                                            <img src="{{ obj.file.url }}" alt="{{ obj.ticket.title }}" class="mt-1 click-full-size"
                                                 width="100" height="60">
                                        {% endif %}
                                    </div>
                                </div>
                            {% endfor %}
                        </div>
                        {% if ticket.status == 'open' %}
                            <form method="POST" action="{% url 'ticket:ticket_create_message' ticket.pk %}" class="d-flex flex-column w-100 ticket-message-send">
                                {% csrf_token %}
                                <label class="form-label">
                                    <small>متن پیام</small>
                                    <textarea name="text" rows="3" placeholder="متن خود را وارد کنید" class="form-control mt-1"></textarea>
                                </label>
                                <button type="submit" class="btn btn-sm btn-warning align-self-end fw-semibold mt-1">ارسال</button>
                            </form>
                        {% else %}
                            <div class="w-100 text-center ticket-message-send">
                                <span class="fw-semibold h5">این تیکت بسته شده است</span>
                            </div>
                        {% endif %}
                    </div>
                </div>
                <!-- .End ticket messages section -->

            </div>
        </main>
    </div>
{% endblock %}

{% block scripts %}
    <script src="{% static 'js/menu.js' %}"></script>
{% endblock %}

src/apps/ticket/templates/ticket/ticket_list.html
{% extends 'base_template.html' %}
{% load static %}
{% load filters %}


{% block title %}مدیرمدرن | تیکت ها{% endblock %}

{% block styles %}
    <link rel="stylesheet" href="{% static 'styles/tickets.css' %}">
    <link rel="stylesheet" href="{% static 'styles/menu.css' %}">
{% endblock %}

{% block content %}
    <!-- Start Sidebar menu -->
    {% include 'includes/menus/side_menu.html' %}
    <!-- .End Sidebar menu -->

    <div class="container-fluid col-md-10 pb-1">
        <main class="main w-100 p-md-4 p-2">
            <h5 class="fw-semibold text-white text-md-end text-center mt-3">تیکت ها</h5>

            <div class="d-flex gap-5 mt-md-4 mt-3">
                <!-- Start tickets section -->
                <div class="d-flex flex-column p-2 ticket-main">
                    <div class="rounded-3 mb-3">
                        <a href="{% url 'ticket:create_ticket' %}" class="btn btn-warning w-100 fw-semibold">تیکت جدید</a>
                    </div>

                    <div class="ticket-self-box">
                        {% for obj in tickets %}
                            <a href="{{ obj.get_absolute_url }}" title="مشاهده" class="d-flex flex-column rounded-3 ticket-box">
                                <div class="ticket-tag {% if obj.status == 'open' %}bg-success{% else %}bg-danger{% endif %}">
                                    <small class="text-white">{{ obj.get_status_display }}</small>
                                </div>
                                <div class="text-white ticket-box-head">
                                    <h5>{{ obj.title }}</h5>
                                </div>
                                <div class="d-flex gap-4 py-2 px-3 text-white ticket-box-body">
                                    <div class="d-flex flex-column">
                                        <small class="opacity-75">شناسه</small>
                                        <span class="fw-semibold">{{ obj.id }}</span>
                                    </div>
                                    <div class="d-flex flex-column me-1">
                                        <small class="opacity-75">فعالیت</small>
                                        <span class="fw-semibold datetime-convert">{{ obj.get_created_date }}</span>
                                    </div>
                                    <div class="d-flex flex-column me-1">
                                        <small class="opacity-75">نوع</small>
                                        <span class="fw-semibold">{{ obj.get_type_label|truncatechars:11 }}</span>
                                    </div>
                                </div>
                            </a>
                        {% empty %}
                            <div class="w-100"></div>
                        {% endfor %}
                    </div>
                </div>
                <!-- .End tickets section -->

                <!-- Start ticket messages section -->
                <div class="d-flex flex-column gap-4 text-white w-100 ticket-detail-main">
                    <span class="fw-semibold h5">ارسال تیکت جدید</span>

                    <form method="POST" action="{% url 'ticket:create_ticket' %}" enctype="multipart/form-data"
                          class="d-flex flex-wrap gap-2 text-white w-100">
                        {% csrf_token %}
                        <label class="form-label flex-grow-1">
                            <span>عنوان تیکت</span>
                            <input type="text" name="title" placeholder="عنوان تیکت را وارد کنید" required class="form-control mt-1">
                        </label>
                        <label class="form-label flex-grow-1">
                            <span>نوع تیکت</span>
                            <select name="type" id="id_type" class="form-select mt-1">
                                <option value="general" selected>مشکل عمومی/پیشنهاد</option>
                                <option value="technical">مشکل فنی</option>
                            </select>
                        </label>
                        <label class="form-label w-100 mt-2">
                            <span class="me-1">متن تیکت</span>
                            <textarea name="text"  placeholder="متن تیکت را وارد کنید" rows="5" required
                                      maxlength="512" class="form-control mt-1"></textarea>
                        </label>
                        <label class="form-label w-100 mt-1">
                            <span class="me-1">فایل مرتبط</span>
                            <input type="file" name="file" accept="image/jpeg, image/png" class="form-control mt-1">
                        </label>
                        <button type="submit" class="btn btn-warning fw-semibold w-100 mt-4">ثبت تیکت</button>
                    </form>
                </div>
                <!-- .End ticket messages section -->

            </div>
        </main>
    </div>
{% endblock %}

{% block scripts %}
    <script src="{% static 'js/menu.js' %}"></script>
    <script>
    </script>
{% endblock %}

src/apps/ticket/templates/ticket/tickets_create.html
{% extends 'base_template.html' %}
{% load static %}
{% load filters %}


{% block title %}مدیرمدرن | تیکت ها{% endblock %}

{% block styles %}
    <link rel="stylesheet" href="{% static 'styles/tickets.css' %}">
    <link rel="stylesheet" href="{% static 'styles/menu.css' %}">
{% endblock %}

{% block content %}
    <!-- Start Sidebar menu -->
    {% include 'includes/menus/side_menu.html' %}
    <!-- .End Sidebar menu -->

    <div class="container-fluid col-md-10 pb-1">
        <main class="main w-100 p-md-4 p-2">
            <h5 class="fw-semibold text-white text-md-end text-center mt-3">تیکت ها</h5>

            <div class="d-flex gap-5 mt-md-4 mt-3">
                <!-- Start tickets section -->
                <div class="d-md-flex d-none flex-column p-2 ticket-main">
                    <div class="rounded-3 mb-3">
                        <a href="#" class="btn btn-warning w-100 fw-semibold">تیکت جدید</a>
                    </div>

                    <div class="ticket-self-box">
                        {% for obj in tickets %}
                            <a href="{{ obj.get_absolute_url }}" title="مشاهده" class="d-flex flex-column rounded-3 ticket-box">
                                <div class="ticket-tag {% if obj.status == 'open' %}bg-success{% else %}bg-danger{% endif %}">
                                    <small class="text-white">{{ obj.get_status_display }}</small>
                                </div>
                                <div class="text-white ticket-box-head">
                                    <h5>{{ obj.title }}</h5>
                                </div>
                                <div class="d-flex gap-4 py-2 px-3 text-white ticket-box-body">
                                    <div class="d-flex flex-column">
                                        <small class="opacity-75">شناسه</small>
                                        <span class="fw-semibold">{{ obj.id }}</span>
                                    </div>
                                    <div class="d-flex flex-column me-1">
                                        <small class="opacity-75">فعالیت</small>
                                        <span class="fw-semibold datetime-convert">{{ obj.get_created_date }}</span>
                                    </div>
                                    <div class="d-flex flex-column me-1">
                                        <small class="opacity-75">نوع</small>
                                        <span class="fw-semibold">{{ obj.get_type_label|truncatechars:11 }}</span>
                                    </div>
                                </div>
                            </a>
                        {% empty %}
                            <div class="w-100"></div>
                        {% endfor %}
                    </div>
                </div>
                <!-- .End tickets section -->

                <!-- Start ticket messages section -->
                <div class="d-flex flex-column gap-4 text-white w-100 mt-md-0 mt-2 ticket-detail-main">
                    <div class="d-flex justify-content-between">
                        <span class="fw-semibold h5">ارسال تیکت جدید</span>
                        <a href="{% url 'ticket:ticket_list' %}" class="btn btn-danger bi bi-x-lg pb-0 d-md-none d-block"></a>
                    </div>

                    <form method="POST" action="{% url 'ticket:create_ticket' %}" enctype="multipart/form-data"
                          class="d-flex flex-wrap gap-2 text-white w-100">
                        {% csrf_token %}
                        <label class="form-label flex-grow-1">
                            <span>عنوان تیکت</span>
                            <input type="text" name="title" placeholder="عنوان تیکت را وارد کنید" required class="form-control mt-1">
                        </label>
                        <label class="form-label flex-grow-1">
                            <span>نوع تیکت</span>
                            <select name="type" class="form-select mt-1">
                                <option value="general" selected>مشکل عمومی/پیشنهاد</option>
                                <option value="technical">مشکل فنی</option>
                            </select>
                        </label>
                        <label class="form-label w-100 mt-2">
                            <span class="me-1">متن تیکت</span>
                            <textarea name="text"  placeholder="متن تیکت را وارد کنید" rows="5" required
                                      maxlength="512" class="form-control mt-1"></textarea>
                        </label>
                        <label class="form-label w-100 mt-1">
                            <span class="me-1">فایل مرتبط</span>
                            <input type="file" name="file" accept="image/jpeg, image/png" class="form-control mt-1">
                        </label>
                        <button type="submit" class="btn btn-warning fw-semibold w-100 mt-4">ثبت تیکت</button>
                    </form>
                </div>
                <!-- .End ticket messages section -->

            </div>
        </main>
    </div>
{% endblock %}

{% block scripts %}
    <script src="{% static 'js/menu.js' %}"></script>
{% endblock %}