src/apps/account/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path
from . import views


app_name = 'account'

urlpatterns = [
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(next_page='account:login'), name='logout'),

    path('register/', views.RegisterView.as_view(), name='register'),
    path('register/send-code/', views.SendCodeView.as_view(), name='send_code'),
    path('register/verify/', views.VerifyPhoneNumberView.as_view(), name='verify_phone'),

    path('password/reset/', views.GetPhoneNumberView.as_view(), name='get_phone_number'),
    path('password/reset/confirm/', views.ResetPassConfirmView.as_view(), name='reset_pass_confirm'),
    path('password/reset/complete/', views.ResetPassCompleteView.as_view(), name='reset_pass_complete'),
    path('password/edit/', views.EditPasswordView.as_view(), name='edit_password'),

    path('profile/details/', views.UserProfileView.as_view(), name='profile_details'),
]

src/apps/course/urls.py
from django.urls import path, re_path
from . import views


app_name = 'course'

urlpatterns = [
    path('', views.CoursesListView.as_view(), name='course_list'),
    path('my-list/', views.UserCourseListView.as_view(), name='user_course_list'),
    path('purchase/', views.PurchaseCourseView.as_view(), name='purchase_course'),
    path('add/', views.AddCourseView.as_view(), name='add_course'),
    re_path(r'(?P<slug>[-\w]+)/', views.CourseDetailView.as_view(), name='course_detail'),
]

src/apps/customers/urls.py
from django.urls import path
from . import views

app_name = 'customers'

urlpatterns = [
    path('', views.ServicesListView.as_view(), name='services_list'),
    path('<int:pk>/menu/', views.DigitalMenuView.as_view(), name='digital_menu'),
    path('survey/', views.AddCustomerSurveysView.as_view(), name='add_survey'),
    path('survey/list/', views.CustomerSurveysListView.as_view(), name='surveys_list'),

    path('counseling/add', views.CounselingAddView.as_view(), name='counseling_add'),
]

src/apps/ticket/urls.py
from django.urls import path
from . import views


app_name = 'ticket'

urlpatterns = [
    path('', views.TicketListView.as_view(), name='ticket_list'),
    path('create/', views.TicketCreateView.as_view(), name='create_ticket'),
    path('<int:pk>/', views.TicketDetailsView.as_view(), name='ticket_details'),
    path('<int:pk>/message/', views.CreateMessageView.as_view(), name='ticket_create_message'),
]

src/config/urls.py
from django.conf.urls.static import static
from django.urls import path, include
from django.contrib import admin
from django.conf import settings

from azbankgateways.urls import az_bank_gateways_urls


urlpatterns = [
    path('admin/', admin.site.urls),
    path('tinymce/', include('tinymce.urls')),
    path('bankgateways/', az_bank_gateways_urls()),
    path('account/', include('apps.account.urls', namespace='account')),
    path('', include('apps.public.urls', namespace='public')),
    path('course/', include('apps.course.urls', namespace='course')),
    path('ticketing/', include('apps.ticket.urls', namespace='ticket')),
    path('customers/', include('apps.customers.urls', namespace='customers')),
    path('subscription/', include('apps.subscription.urls', namespace='subscription')),
    path('restaurant/', include('apps.restaurant.urls', namespace='restaurant')),
    path('payment/', include('apps.payment.urls', namespace='payment')),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/apps/restaurant/views/menu.py
from django.shortcuts import get_object_or_404, reverse, redirect
from django.views.generic import TemplateView, View, FormView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Sum, F, PositiveIntegerField
from django.db.utils import DataError, DatabaseError
from django.utils.translation import gettext as _
from django.db.models.functions import Cast
from django.core.paginator import Paginator
from django.contrib import messages

from apps.subscription.mixinx import SubscriptionRequiredMixin
from ..models import (Restaurant, Recipe)
from .. import forms


# Render MenuEngineering view
class MenuEngineeringView(LoginRequiredMixin, TemplateView):
    template_name = 'restaurant/menu_engineering.html'

    def filter(self, objects):
        cat_filter = self.request.GET.get('filter')
        if cat_filter:
            objects = objects.filter(category__title=cat_filter)

        return objects

    def pagination(self, objects):
        page_number = self.request.GET.get('page')
        paginator = Paginator(objects, 15)
        return paginator.get_page(page_number)

    def get_context_data(self, object_list=None, **kwargs):
        context = super(MenuEngineeringView, self).get_context_data(**kwargs)
        restaurant = get_object_or_404(Restaurant, user=self.request.user)

        # Get recipes and filter them
        objects = Recipe.objects.filter(category__restaurant=restaurant, is_material=False).order_by('created_at')
        objects = self.filter(objects)
        page_obj = self.pagination(objects)

        context.update({
            'restaurant': restaurant,
            'page_obj': page_obj,
            'objects': objects.aggregate(
                total_final_price=Sum('final_price'),
                total_service_price=Sum('service_price'),
                total_price_with_factor=Sum('price_with_factor'),
                total_menu_price=Sum('menu_price'),
                total_item_profit=Sum('item_profit'),
                total_food_costs=Sum('food_cost'),
                total_number_sold=Sum('number_sold'),
                total_total_sales=Sum('total_sales'),
                total_total_cost=Sum('total_cost'),
                total_total_profit=Sum('total_profit'),
            ),
            'each_item_percentage_share': 0.7 / (objects.count() or 1),
        })

        return context


# Update Restaurant ServicesFee view
class UpdateServicesFeeView(SubscriptionRequiredMixin, View):
    """ Update restaurant services fee """

    def get_redirect_url(self, request):
        return reverse('restaurant:menu_engineering') + f'?filter={request.GET.get("filter")}'

    def post(self, request):
        fee = int(request.POST.get('services_fee'))
        restaurant = get_object_or_404(Restaurant, user=self.request.user)

        restaurant.services_fee = fee
        restaurant.save()

        # Update recipes service_prices based on services_fee
        recipes = Recipe.objects.filter(category__restaurant=restaurant, is_material=False)
        recipes.update(service_price=Cast(F('final_price') * (fee / 100), output_field=PositiveIntegerField()))
        recipes.update(price_with_factor=Cast(F('final_price') * F('factor') + F('service_price'), output_field=PositiveIntegerField()))

        messages.success(request, _('Services fee updated'))
        return redirect(self.get_redirect_url(request))  # Redirect with GET parameters


# UpdateRecipe view
class UpdateRecipeView(SubscriptionRequiredMixin, FormView):
    template_name = 'restaurant/menu_engineering.html'
    form_class = forms.UpdateRecipeForm

    def get_success_url(self):
        return reverse('restaurant:menu_engineering') + f'?filter={self.request.GET.get("filter")}&page={self.request.GET.get("page")}'

    def get_form(self, form_class=None):
        obj = get_object_or_404(Recipe, category__restaurant__user=self.request.user, pk=self.kwargs.get('pk'))
        return forms.UpdateRecipeForm(data=self.request.POST, instance=obj)
    
    def form_valid(self, form):
        form.save(commit=False)
        
        messages.success(self.request, _('Item updated successfully'))
        return super().form_valid(form)

src/templates/includes/menus/side_menu.html
{% load static %}

<nav class="menu-fixed-right menu overflow-auto col-md-2" id="SideMenu">
    <div class="menu-toggle-btn menu">
        <i role="button" class="bi bi-list menu-toggle-icon"></i>
    </div>

    <div class="inner-menu-fixed-right">
        <div class="menu-toggle-btn-close">
            <i role="button" class="bi bi-x-lg" style="-webkit-text-stroke: 0.6pt;"></i>
        </div>
        <div class="up-menu">
            <div class="profile">
                <img src="{{ user.profile.get_image_url }}" class="rounded-circle mt-3 me-3" width="75" height="75"
                     alt="Profile picture" style="object-fit: cover;">
                <div class="d-flex flex-column align-items-start mt-3 me-2">
                    <span class="mt-2">
                        {{ user.profile.place_name|default:'بدون عنوان' }}
                    </span>
                    <small class="mt-1">
                        {{ user.profile.province|default:'' }}، {{ user.profile.city|default:'' }}
                    </small>
                </div>
            </div>
        </div>
        <div class="content-menu mt-2">
            <ul class="list">
                <li class="item-menu">
                    <a href="{% url 'public:index' %}"
                       class="{% if request.resolver_match.url_name == 'index' %}active{% endif %}">
                        <span class="d-flex align-items-center" style="margin-right: 12px;">
                            <i class="bi bi-house mt-2" style="font-size: 25px;"></i>
                        </span>
                        <span class="fw-semibold">خانه</span>
                    </a>
                </li>
                <li class="item-menu">
                    <a href="{% url 'account:profile_details' %}"
                       class="{% if request.resolver_match.url_name == 'profile_details' %}active{% endif %}">
                        <span class="d-flex align-items-center" style="margin-right: 12px;">
                            <i class="bi bi-person-badge mt-2" style="font-size: 25px;"></i>
                        </span>
                        <span class="fw-semibold">پروفایل</span>
                    </a>
                </li>
                <li class="item-menu">
                    <a href="{% url 'ticket:ticket_list' %}"
                       class="{% if request.resolver_match.app_name == 'ticket' %}active{% endif %}">
                        <span class="d-flex align-items-center" style="margin-right: 12px;">
                            <i class="bi bi-ticket-detailed mt-2" style="font-size: 24px;"></i>
                        </span>
                        <span class="fw-semibold me-1">تیکت‌ ها</span>
                    </a>
                </li>

                <li class="item-menu">
                    <a href="{% url 'public:index' %}?app_course"
                       class="{% if request.GET.app_course == 'course' %}active{% endif %}">
                        <span class="d-flex align-items-center" style="margin-right: 12px;">
                            <i class="bi bi-mortarboard mt-2" style="font-size: 23px;"></i>
                        </span>
                        <span class="fw-semibold">آموزش اپ</span>
                    </a>
                </li>
                <li class="item-menu">
                    <a href="{% url 'course:course_list' %}"
                       class="{% if request.resolver_match.app_name == 'course' %}active{% endif %}">
                        <span class="d-flex align-items-center" style="margin-right: 12px;">
                            <i class="bi bi-mortarboard mt-2" style="font-size: 23px;"></i>
                        </span>
                        <span class="fw-semibold">دوره ها</span>
                    </a>
                </li>
                <li class="item-menu">
                    <a href="{% url 'customers:counseling_add' %}"
                       class="{% if request.resolver_match.app_name == 'customers' %}active{% endif %}">
                        <span class="d-flex align-items-center" style="margin-right: 12px;">
                            <i class="bi bi-clipboard-data mt-2" style="font-size: 23px;"></i>
                        </span>
                        <span class="fw-semibold">مشاوره
                            <b class="badge bg-success m-1">رایگان</b>
                        </span>
                    </a>
                </li>
                <li class="item-menu">
                    <a href="{% url 'subscription:subscription_list' %}"
                       class="{% if request.resolver_match.app_name == 'subscription' %}active{% endif %}">
                        <span class="d-flex align-items-center" style="margin-right: 13px;">
                            <i class="bi bi-patch-check mt-2" style="font-size: 23px;"></i>
                        </span>
                        <span class="fw-semibold">تهیه اشتراک</span>
                    </a>
                </li>
                <li class="item-menu">
                    <a data-bs-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false"
                       aria-controls="collapseExample">
                        <span class="d-flex align-items-center" style="margin-right: 12px;">
                            <i class="bi bi-cup-hot mt-2" style="font-size: 24px;"></i>
                        </span>
                        <span class="fw-semibold me-1">مدیریت منو</span>
                    </a>
                    <div class="{% if request.resolver_match.app_name == 'restaurant' %}collapsed{% else %}collapse{% endif %}"
                         id="collapseExample">
                        <ul class="menu-sub-item pe-3">
                            <li class="item-menu">
                                <a href="{% url 'restaurant:profile_index' %}"
                                   class="{% if request.resolver_match.url_name == 'profile_index' %}active{% endif %}">
                                    <span class="d-flex align-items-center" style="margin-right: 12px;">
                                        <i class="bi bi-currency-dollar mt-2" style="font-size: 19px;"></i>
                                    </span>
                                    <span class="fw-semibold me-1">سرمایه و هزینه</span>
                                </a>
                            </li>
                            <li class="item-menu">
                                <a href="{% url 'restaurant:profile_sales_estimate' %}"
                                   class="{% if request.resolver_match.url_name == 'profile_sales_estimate' %}active{% endif %}">
                                    <span class="d-flex align-items-center" style="margin-right: 12px;">
                                        <i class="bi bi-card-list mt-2" style="font-size: 19px;"></i>
                                    </span>
                                    <span class="fw-semibold me-1">برآورد فروش</span>
                                </a>
                            </li>
                            <li class="item-menu">
                                <a href="{% url 'restaurant:raw_materials' %}"
                                   class="{% if request.resolver_match.url_name == 'raw_materials' or request.resolver_match.url_name == 'raw_materials_reduce_form' %}active{% endif %}">
                                    <span class="d-flex align-items-center" style="margin-right: 12px;">
                                        <i class="bi bi-box2 mt-2" style="font-size: 19px;"></i>
                                    </span>
                                    <span class="fw-semibold me-1">مواد اولیه</span>
                                </a>
                            </li>
                            <li class="item-menu">
                                <a href="{% url 'restaurant:recipes' %}"
                                   class="{% if request.resolver_match.url_name == 'recipes' or request.resolver_match.url_name == 'recipe_details' %}active{% endif %}">
                                    <span class="d-flex align-items-center" style="margin-right: 12px;">
                                        <i class="bi bi-receipt mt-2" style="font-size: 19px;"></i>
                                    </span>
                                    <span class="fw-semibold me-1">رسپی غذاها</span>
                                </a>
                            </li>
                            <li class="item-menu">
                                <a href="{% url 'restaurant:preparations' %}"
                                   class="{% if request.resolver_match.url_name == 'preparations' or request.resolver_match.url_name == 'preparation_details' %}active{% endif %}">
                                    <span class="d-flex align-items-center" style="margin-right: 12px;">
                                        <i class="bi bi-bag-check mt-2" style="font-size: 19px;"></i>
                                    </span>
                                    <span class="fw-semibold me-1 mt-1">آماده سازی‌ها</span>
                                </a>
                            </li>
                            <li class="item-menu">
                                <a href="{% url 'restaurant:menu_engineering' %}"
                                   class="{% if request.resolver_match.url_name == 'menu_engineering' %}active{% endif %}">
                                    <span class="d-flex align-items-center" style="margin-right: 12px;">
                                        <i class="bi bi-journal-richtext mt-2" style="font-size: 20px;"></i>
                                    </span>
                                    <span class="fw-semibold me-1">مهندسی منو</span>
                                </a>
                            </li>

                        </ul>
                    </div>
                </li>
                <li class="item-menu">
                    <a href="{% url 'account:logout' %}">
                        <span class="d-flex align-items-center" style="margin-right: 10px;">
                            <i class="bi bi-door-open mt-2" style="font-size: 25px;"></i>
                        </span>
                        <span class="fw-semibold">خروج</span>
                    </a>
                </li>
            </ul>
        </div>
    </div>
</nav>